# Generated by Django 5.2.4 on 2025-12-27 04:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="equipment",
            name="warranty_info",
        ),
        migrations.RemoveField(
            model_name="maintenancerequest",
            name="subject",
        ),
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee_images/"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="assign_date",
            field=models.DateField(
                blank=True,
                help_text="Date equipment was assigned to current owner",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="description",
            field=models.TextField(
                blank=True, help_text="Internal notes or description of the asset"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipment_images/"
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="scrap_date",
            field=models.DateField(
                blank=True, help_text="Date when equipment was scrapped", null=True
            ),
        ),
        migrations.AddField(
            model_name="equipmentcategory",
            name="responsible_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Manager responsible for this category of assets",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="color",
            field=models.IntegerField(
                default=0, help_text="Color index for Kanban view"
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="name",
            field=models.CharField(
                default="", help_text="Subject/Description of the issue", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="request_date",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date the request was created",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equipment",
            name="warranty_expiry_date",
            field=models.DateField(
                blank=True, help_text="Warranty expiration date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Technician or Manager responsible for the ticket",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="maintenance.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (0, "No Priority"),
                    (1, "Low"),
                    (2, "Medium"),
                    (3, "High"),
                    (4, "Critical"),
                ],
                default=0,
                help_text="Importance level (star rating)",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True, help_text="When the work is planned to happen", null=True
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="maintenance.company",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment",
                to="maintenance.company",
            ),
        ),
        migrations.AddField(
            model_name="equipmentcategory",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_categories",
                to="maintenance.company",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="maintenance.company",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceteam",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_teams",
                to="maintenance.company",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor or manufacturer linked to warranty",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="maintenance.vendor",
            ),
        ),
        migrations.CreateModel(
            name="WorkCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "costs_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost per hour",
                        max_digits=10,
                    ),
                ),
                (
                    "time_efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Capacity time efficiency percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "oee_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=90,
                        help_text="Overall Equipment Effectiveness target percentage",
                        max_digits=5,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alternative_workcenters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="backup_for",
                        to="maintenance.workcenter",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workcenters",
                        to="maintenance.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Work Center",
                "verbose_name_plural": "Work Centers",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="work_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Work center if equipment is part of a manufacturing line",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="maintenance.workcenter",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="work_center",
            field=models.ForeignKey(
                blank=True,
                help_text="Alternative to Equipment - for work center maintenance",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="maintenance.workcenter",
            ),
        ),
    ]
